language: cpp

compiler:
  - g++
 
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libglm-dev libglew-dev libglfw-dev
  - pkg-config --list-all | grep gl
  - mkdir build
  - cd build
  - cmake ..

script: make
